// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: testproto.proto

package testproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_UNKNOWN Status = 0
	Status_OK      Status = 1
	Status_FAILED  Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "OK",
		2: "FAILED",
	}
	Status_value = map[string]int32{
		"UNKNOWN": 0,
		"OK":      1,
		"FAILED":  2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_testproto_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_testproto_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_testproto_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_testproto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_testproto_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Photo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhotoId       int64                  `protobuf:"varint,1,opt,name=photo_id,json=photoId,proto3" json:"photo_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Dimensions    *Dimensions            `protobuf:"bytes,3,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Photo) Reset() {
	*x = Photo{}
	mi := &file_testproto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Photo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Photo) ProtoMessage() {}

func (x *Photo) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Photo.ProtoReflect.Descriptor instead.
func (*Photo) Descriptor() ([]byte, []int) {
	return file_testproto_proto_rawDescGZIP(), []int{1}
}

func (x *Photo) GetPhotoId() int64 {
	if x != nil {
		return x.PhotoId
	}
	return 0
}

func (x *Photo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Photo) GetDimensions() *Dimensions {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

type Dimensions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dimensions) Reset() {
	*x = Dimensions{}
	mi := &file_testproto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dimensions) ProtoMessage() {}

func (x *Dimensions) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dimensions.ProtoReflect.Descriptor instead.
func (*Dimensions) Descriptor() ([]byte, []int) {
	return file_testproto_proto_rawDescGZIP(), []int{2}
}

func (x *Dimensions) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Dimensions) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Attribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          map[string]string      `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_testproto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_testproto_proto_rawDescGZIP(), []int{3}
}

func (x *Attribute) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Options struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OptionalString *string                `protobuf:"bytes,1,opt,name=optional_string,json=optionalString,proto3,oneof" json:"optional_string,omitempty"`
	OptionalInt    *int32                 `protobuf:"varint,2,opt,name=optional_int,json=optionalInt,proto3,oneof" json:"optional_int,omitempty"`
	OptionalPhoto  *Photo                 `protobuf:"bytes,3,opt,name=optional_photo,json=optionalPhoto,proto3,oneof" json:"optional_photo,omitempty"`
	OptionalAttr   *Attribute             `protobuf:"bytes,4,opt,name=optional_attr,json=optionalAttr,proto3,oneof" json:"optional_attr,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_testproto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_testproto_proto_rawDescGZIP(), []int{4}
}

func (x *Options) GetOptionalString() string {
	if x != nil && x.OptionalString != nil {
		return *x.OptionalString
	}
	return ""
}

func (x *Options) GetOptionalInt() int32 {
	if x != nil && x.OptionalInt != nil {
		return *x.OptionalInt
	}
	return 0
}

func (x *Options) GetOptionalPhoto() *Photo {
	if x != nil {
		return x.OptionalPhoto
	}
	return nil
}

func (x *Options) GetOptionalAttr() *Attribute {
	if x != nil {
		return x.OptionalAttr
	}
	return nil
}

type Profile struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	User            *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Photo           *Photo                 `protobuf:"bytes,2,opt,name=photo,proto3" json:"photo,omitempty"`
	LoginTimestamps []int64                `protobuf:"varint,3,rep,packed,name=login_timestamps,json=loginTimestamps,proto3" json:"login_timestamps,omitempty"`
	Gallery         []*Photo               `protobuf:"bytes,4,rep,name=gallery,proto3" json:"gallery,omitempty"`
	Attributes      map[string]*Attribute  `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_testproto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_testproto_proto_rawDescGZIP(), []int{5}
}

func (x *Profile) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Profile) GetPhoto() *Photo {
	if x != nil {
		return x.Photo
	}
	return nil
}

func (x *Profile) GetLoginTimestamps() []int64 {
	if x != nil {
		return x.LoginTimestamps
	}
	return nil
}

func (x *Profile) GetGallery() []*Photo {
	if x != nil {
		return x.Gallery
	}
	return nil
}

func (x *Profile) GetAttributes() map[string]*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Fieldmask     *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=fieldmask,proto3" json:"fieldmask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_testproto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_testproto_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProfileRequest) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *UpdateProfileRequest) GetFieldmask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Fieldmask
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	NextToken     int64                  `protobuf:"varint,2,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_testproto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_testproto_proto_rawDescGZIP(), []int{7}
}

func (x *Result) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Result) GetNextToken() int64 {
	if x != nil {
		return x.NextToken
	}
	return 0
}

type Event struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	EventId int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Types that are valid to be assigned to Changed:
	//
	//	*Event_User
	//	*Event_Photo
	//	*Event_Status
	//	*Event_Details
	//	*Event_Profile
	Changed       isEvent_Changed `protobuf_oneof:"changed"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_testproto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_testproto_proto_rawDescGZIP(), []int{8}
}

func (x *Event) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *Event) GetChanged() isEvent_Changed {
	if x != nil {
		return x.Changed
	}
	return nil
}

func (x *Event) GetUser() *User {
	if x != nil {
		if x, ok := x.Changed.(*Event_User); ok {
			return x.User
		}
	}
	return nil
}

func (x *Event) GetPhoto() *Photo {
	if x != nil {
		if x, ok := x.Changed.(*Event_Photo); ok {
			return x.Photo
		}
	}
	return nil
}

func (x *Event) GetStatus() Status {
	if x != nil {
		if x, ok := x.Changed.(*Event_Status); ok {
			return x.Status
		}
	}
	return Status_UNKNOWN
}

func (x *Event) GetDetails() *anypb.Any {
	if x != nil {
		if x, ok := x.Changed.(*Event_Details); ok {
			return x.Details
		}
	}
	return nil
}

func (x *Event) GetProfile() *Profile {
	if x != nil {
		if x, ok := x.Changed.(*Event_Profile); ok {
			return x.Profile
		}
	}
	return nil
}

type isEvent_Changed interface {
	isEvent_Changed()
}

type Event_User struct {
	User *User `protobuf:"bytes,2,opt,name=user,proto3,oneof"`
}

type Event_Photo struct {
	Photo *Photo `protobuf:"bytes,3,opt,name=photo,proto3,oneof"`
}

type Event_Status struct {
	Status Status `protobuf:"varint,4,opt,name=status,proto3,enum=testproto.Status,oneof"`
}

type Event_Details struct {
	Details *anypb.Any `protobuf:"bytes,5,opt,name=details,proto3,oneof"`
}

type Event_Profile struct {
	Profile *Profile `protobuf:"bytes,6,opt,name=profile,proto3,oneof"`
}

func (*Event_User) isEvent_Changed() {}

func (*Event_Photo) isEvent_Changed() {}

func (*Event_Status) isEvent_Changed() {}

func (*Event_Details) isEvent_Changed() {}

func (*Event_Profile) isEvent_Changed() {}

var File_testproto_proto protoreflect.FileDescriptor

const file_testproto_proto_rawDesc = "" +
	"\n" +
	"\x0ftestproto.proto\x12\ttestproto\x1a\x19google/protobuf/any.proto\x1a google/protobuf/field_mask.proto\"3\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"m\n" +
	"\x05Photo\x12\x19\n" +
	"\bphoto_id\x18\x01 \x01(\x03R\aphotoId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x125\n" +
	"\n" +
	"dimensions\x18\x03 \x01(\v2\x15.testproto.DimensionsR\n" +
	"dimensions\":\n" +
	"\n" +
	"Dimensions\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\"x\n" +
	"\tAttribute\x122\n" +
	"\x04tags\x18\x01 \x03(\v2\x1e.testproto.Attribute.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x02\n" +
	"\aOptions\x12,\n" +
	"\x0foptional_string\x18\x01 \x01(\tH\x00R\x0eoptionalString\x88\x01\x01\x12&\n" +
	"\foptional_int\x18\x02 \x01(\x05H\x01R\voptionalInt\x88\x01\x01\x12<\n" +
	"\x0eoptional_photo\x18\x03 \x01(\v2\x10.testproto.PhotoH\x02R\roptionalPhoto\x88\x01\x01\x12>\n" +
	"\roptional_attr\x18\x04 \x01(\v2\x14.testproto.AttributeH\x03R\foptionalAttr\x88\x01\x01B\x12\n" +
	"\x10_optional_stringB\x0f\n" +
	"\r_optional_intB\x11\n" +
	"\x0f_optional_photoB\x10\n" +
	"\x0e_optional_attr\"\xc6\x02\n" +
	"\aProfile\x12#\n" +
	"\x04user\x18\x01 \x01(\v2\x0f.testproto.UserR\x04user\x12&\n" +
	"\x05photo\x18\x02 \x01(\v2\x10.testproto.PhotoR\x05photo\x12)\n" +
	"\x10login_timestamps\x18\x03 \x03(\x03R\x0floginTimestamps\x12*\n" +
	"\agallery\x18\x04 \x03(\v2\x10.testproto.PhotoR\agallery\x12B\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2\".testproto.Profile.AttributesEntryR\n" +
	"attributes\x1aS\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.testproto.AttributeR\x05value:\x028\x01\"~\n" +
	"\x14UpdateProfileRequest\x12,\n" +
	"\aprofile\x18\x01 \x01(\v2\x12.testproto.ProfileR\aprofile\x128\n" +
	"\tfieldmask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldmask\";\n" +
	"\x06Result\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"next_token\x18\x02 \x01(\x03R\tnextToken\"\x8d\x02\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12%\n" +
	"\x04user\x18\x02 \x01(\v2\x0f.testproto.UserH\x00R\x04user\x12(\n" +
	"\x05photo\x18\x03 \x01(\v2\x10.testproto.PhotoH\x00R\x05photo\x12+\n" +
	"\x06status\x18\x04 \x01(\x0e2\x11.testproto.StatusH\x00R\x06status\x120\n" +
	"\adetails\x18\x05 \x01(\v2\x14.google.protobuf.AnyH\x00R\adetails\x12.\n" +
	"\aprofile\x18\x06 \x01(\v2\x12.testproto.ProfileH\x00R\aprofileB\t\n" +
	"\achanged*)\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02B1Z/github.com/mennanov/fmutils/testproto;testprotob\x06proto3"

var (
	file_testproto_proto_rawDescOnce sync.Once
	file_testproto_proto_rawDescData []byte
)

func file_testproto_proto_rawDescGZIP() []byte {
	file_testproto_proto_rawDescOnce.Do(func() {
		file_testproto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testproto_proto_rawDesc), len(file_testproto_proto_rawDesc)))
	})
	return file_testproto_proto_rawDescData
}

var file_testproto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_testproto_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_testproto_proto_goTypes = []any{
	(Status)(0),                   // 0: testproto.Status
	(*User)(nil),                  // 1: testproto.User
	(*Photo)(nil),                 // 2: testproto.Photo
	(*Dimensions)(nil),            // 3: testproto.Dimensions
	(*Attribute)(nil),             // 4: testproto.Attribute
	(*Options)(nil),               // 5: testproto.Options
	(*Profile)(nil),               // 6: testproto.Profile
	(*UpdateProfileRequest)(nil),  // 7: testproto.UpdateProfileRequest
	(*Result)(nil),                // 8: testproto.Result
	(*Event)(nil),                 // 9: testproto.Event
	nil,                           // 10: testproto.Attribute.TagsEntry
	nil,                           // 11: testproto.Profile.AttributesEntry
	(*fieldmaskpb.FieldMask)(nil), // 12: google.protobuf.FieldMask
	(*anypb.Any)(nil),             // 13: google.protobuf.Any
}
var file_testproto_proto_depIdxs = []int32{
	3,  // 0: testproto.Photo.dimensions:type_name -> testproto.Dimensions
	10, // 1: testproto.Attribute.tags:type_name -> testproto.Attribute.TagsEntry
	2,  // 2: testproto.Options.optional_photo:type_name -> testproto.Photo
	4,  // 3: testproto.Options.optional_attr:type_name -> testproto.Attribute
	1,  // 4: testproto.Profile.user:type_name -> testproto.User
	2,  // 5: testproto.Profile.photo:type_name -> testproto.Photo
	2,  // 6: testproto.Profile.gallery:type_name -> testproto.Photo
	11, // 7: testproto.Profile.attributes:type_name -> testproto.Profile.AttributesEntry
	6,  // 8: testproto.UpdateProfileRequest.profile:type_name -> testproto.Profile
	12, // 9: testproto.UpdateProfileRequest.fieldmask:type_name -> google.protobuf.FieldMask
	1,  // 10: testproto.Event.user:type_name -> testproto.User
	2,  // 11: testproto.Event.photo:type_name -> testproto.Photo
	0,  // 12: testproto.Event.status:type_name -> testproto.Status
	13, // 13: testproto.Event.details:type_name -> google.protobuf.Any
	6,  // 14: testproto.Event.profile:type_name -> testproto.Profile
	4,  // 15: testproto.Profile.AttributesEntry.value:type_name -> testproto.Attribute
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_testproto_proto_init() }
func file_testproto_proto_init() {
	if File_testproto_proto != nil {
		return
	}
	file_testproto_proto_msgTypes[4].OneofWrappers = []any{}
	file_testproto_proto_msgTypes[8].OneofWrappers = []any{
		(*Event_User)(nil),
		(*Event_Photo)(nil),
		(*Event_Status)(nil),
		(*Event_Details)(nil),
		(*Event_Profile)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testproto_proto_rawDesc), len(file_testproto_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testproto_proto_goTypes,
		DependencyIndexes: file_testproto_proto_depIdxs,
		EnumInfos:         file_testproto_proto_enumTypes,
		MessageInfos:      file_testproto_proto_msgTypes,
	}.Build()
	File_testproto_proto = out.File
	file_testproto_proto_goTypes = nil
	file_testproto_proto_depIdxs = nil
}
