name: Tests coverage

on: [ "push", "pull_request" ]

jobs:

  build:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      - name: Run tests with coverage
        run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...
      - uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true