name: Linter

on: [ "push", "pull_request" ]

jobs:

  build:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Go vet
        run: go vet ./...
